CREATE TABLE membro (
    id BIGSERIAL PRIMARY KEY,
    nome_completo VARCHAR(150) NOT NULL,
    sexo VARCHAR(20),
    data_nascimento DATE,
    cidade_nascimento VARCHAR(120),
    cep_nascimento VARCHAR(8),
    uf_nascimento VARCHAR(2),
    cidade_atual VARCHAR(120),
    cep_atual VARCHAR(8),
    uf_atual VARCHAR(2),
    estado_civil VARCHAR(30),
    data_casamento DATE,
    conjuge VARCHAR(150),
    mae VARCHAR(150),
    pai VARCHAR(150),
    celular VARCHAR(11),
    email VARCHAR(150),
    tipo_membro VARCHAR(20),
    situacao VARCHAR(120),
    data_batismo DATE,
    pastor_oficiante VARCHAR(120),
    data_batismo_espirito_santo DATE,
    data_admissao DATE,
    admitido_por VARCHAR(20),
    admitido_por_outro VARCHAR(120),
    ministerio_principal VARCHAR(120),
    funcao_ministerial VARCHAR(120),
    departamento_principal VARCHAR(120),
    funcao_departamental VARCHAR(120),
    data_remocao DATE,
    removido_por VARCHAR(150),
    observacoes TEXT
);
